# Generated by Django 5.0.14 on 2026-01-19 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('MEN', 'Мужская вienspēle'), ('WOMEN', 'Женская вienspēle'), ('MIXED', 'Смешанные')], max_length=10, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('UPCOMING', 'Предстоящий'), ('ONGOING', 'Идёт'), ('FINISHED', 'Завершён')], default='UPCOMING', max_length=10, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место проведения')),
                ('max_participants', models.IntegerField(default=16, verbose_name='Максимум участников')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournaments/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=50, verbose_name='Раунд')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Запланирован'), ('IN_PROGRESS', 'Идёт'), ('FINISHED', 'Завершён'), ('CANCELLED', 'Отменён')], default='SCHEDULED', max_length=15, verbose_name='Статус')),
                ('player1_set1', models.IntegerField(blank=True, null=True, verbose_name='Сет 1 (Игрок 1)')),
                ('player1_set2', models.IntegerField(blank=True, null=True, verbose_name='Сет 2 (Игрок 1)')),
                ('player1_set3', models.IntegerField(blank=True, null=True, verbose_name='Сет 3 (Игрок 1)')),
                ('player2_set1', models.IntegerField(blank=True, null=True, verbose_name='Сет 1 (Игрок 2)')),
                ('player2_set2', models.IntegerField(blank=True, null=True, verbose_name='Сет 2 (Игрок 2)')),
                ('player2_set3', models.IntegerField(blank=True, null=True, verbose_name='Сет 3 (Игрок 2)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['scheduled_date', 'round'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(blank=True, null=True, verbose_name='Номер посева')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['seed', 'registered_at'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
