# Generated by Django 5.0.14 on 2026-01-19 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('region', models.CharField(choices=[('NORTH', 'Север'), ('SOUTH', 'Юг'), ('CENTER', 'Центр'), ('WEST', 'Запад'), ('EAST', 'Восток')], max_length=10, verbose_name='Регион')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость часа')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('working_hours', models.CharField(default='07:00 - 00:00', max_length=100, verbose_name='Часы работы')),
                ('facilities', models.TextField(blank=True, help_text='Раздевалки, душ, парковка и т.д.', verbose_name='Удобства')),
                ('has_indoor', models.BooleanField(default=False, verbose_name='Крытый корт')),
                ('has_outdoor', models.BooleanField(default=True, verbose_name='Открытый корт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Корт',
                'verbose_name_plural': 'Корты',
                'ordering': ['city', 'region', 'name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='actual_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата игры'),
        ),
        migrations.AddField(
            model_name='match',
            name='balls_confirmed',
            field=models.BooleanField(default=False, help_text='Не менее 3 новых мячей', verbose_name='Мячи согласованы'),
        ),
        migrations.AddField(
            model_name='match',
            name='contact_initiated_by',
            field=models.ForeignKey(blank=True, help_text='Принимающая сторона', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор контакта'),
        ),
        migrations.AddField(
            model_name='match',
            name='court_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость корта'),
        ),
        migrations.AddField(
            model_name='match',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Время на каждую игру - 1 неделя', null=True, verbose_name='Дедлайн на игру'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_confirmed_by_player1',
            field=models.BooleanField(default=False, verbose_name='Счет подтвержден игроком 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_confirmed_by_player2',
            field=models.BooleanField(default=False, verbose_name='Счет подтвержден игроком 2'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=10, verbose_name='Взнос за участие'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='level',
            field=models.CharField(choices=[('1.5-2.5', '3я категория (1.5-2.5)'), ('2.5-3.5', '2я категория (2.5-3.5)'), ('3.5-4.5', '1я категория (3.5-4.5)'), ('4.5-5.5', 'Мастерс (4.5-5.5)'), ('5.5-6.5', 'Профи (5.5-6.5)')], default='2.5-3.5', max_length=10, verbose_name='Уровень игры'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_rounds',
            field=models.IntegerField(default=3, help_text='Каждый игрок играет указанное количество матчей', verbose_name='Количество игр'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_description',
            field=models.TextField(blank=True, default='Победитель получает бесплатное участие в следующем турнире', verbose_name='Описание приза'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='region',
            field=models.CharField(choices=[('NORTH', 'Север'), ('SOUTH', 'Юг'), ('CENTER', 'Центр'), ('ALL', 'Вся Москва')], default='ALL', max_length=10, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='scoring_system',
            field=models.CharField(choices=[('OLYMPIC', 'Олимпийская система'), ('ROUND_ROBIN', 'Круговая система')], default='OLYMPIC', max_length=15, verbose_name='Система проведения'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status_detail',
            field=models.CharField(choices=[('ACCEPTING', 'Прием заявок'), ('IN_PROGRESS', 'Идут игры'), ('COMPLETED', 'Завершен')], default='ACCEPTING', max_length=15, verbose_name='Детальный статус'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('MULTI_DAY', 'Многодневный'), ('WEEKEND', 'Выходного дня')], default='MULTI_DAY', max_length=15, verbose_name='Тип турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('MEN', 'Мужская'), ('WOMEN', 'Женская'), ('MIXED', 'Смешанные')], max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=8, verbose_name='Максимум участников'),
        ),
        migrations.AddField(
            model_name='match',
            name='court_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.courtlocation', verbose_name='Корт'),
        ),
        migrations.CreateModel(
            name='PartnerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('TENNIS', 'Теннис'), ('TABLE_TENNIS', 'Настольный теннис'), ('BADMINTON', 'Бадминтон'), ('BEACH_TENNIS', 'Пляжный теннис'), ('PADEL', 'Падл-теннис'), ('SQUASH', 'Сквош'), ('PICKLEBALL', 'Пиклбол')], default='TENNIS', max_length=20, verbose_name='Вид спорта')),
                ('skill_level', models.CharField(choices=[('1.0', '1.0 - Начинающий'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0 - Средний'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5 - Продвинутый'), ('5.0', '5.0'), ('5.5', '5.5'), ('6.0', '6.0 - Профессионал'), ('6.5', '6.5')], max_length=5, verbose_name='Уровень игры (NTRP)')),
                ('preferred_time', models.CharField(help_text='Например: будни вечером, выходные днем', max_length=200, verbose_name='Предпочитаемое время')),
                ('preferred_location', models.CharField(help_text='Район или название корта', max_length=200, verbose_name='Предпочитаемое место')),
                ('contact_info', models.TextField(blank=True, verbose_name='Контактная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная заявка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_searches', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поиск партнера',
                'verbose_name_plural': 'Поиск партнеров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntrp_level', models.CharField(default='3.0', max_length=5, verbose_name='Уровень NTRP')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Матчей сыграно')),
                ('matches_won', models.IntegerField(default=0, verbose_name='Матчей выиграно')),
                ('tournament_wins', models.IntegerField(default=0, verbose_name='Побед в турнирах')),
                ('points', models.IntegerField(default=1000, verbose_name='Рейтинговые очки')),
                ('rank_position', models.IntegerField(blank=True, null=True, verbose_name='Позиция в рейтинге')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_rating', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['-points', 'rank_position'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Сумма бонуса')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('PAID', 'Выплачено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referred', 'tournament')},
            },
        ),
    ]
