# Generated by Django 5.0.14 on 2026-01-19 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_courtlocation_match_actual_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="Рейтинговые очки")),
                (
                    "change",
                    models.IntegerField(
                        default=0,
                        help_text="Положительное значение - рост, отрицательное - падение",
                        verbose_name="Изменение",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Причина"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rating_changes",
                        to="tournaments.match",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rating_changes",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "История рейтинга",
                "verbose_name_plural": "История рейтингов",
                "ordering": ["-created_at"],
            },
        ),
    ]
